### ISSUE TITLE
windows install error

### ISSUE THREAD

**Issue by zouqinxiang** [LER0ever/EverVim#10]
本机上安装出现如下错误:

![error](https://cloud.githubusercontent.com/assets/3139340/26359721/cb7e5ff2-4008-11e7-9957-630df91f446a.png)
系统版本：win10专业版  14393

**Comment by LER0ever** [comment]
这是因为第一次启动的时候插件还没有安装，请按照安装指示执行 `:PlugInstall` 来安装所有插件。

**Comment by zouqinxiang** [comment]
OK解决了，安装过程中vimproc安装失败，手动nmake了一下就好了.

**Comment by LER0ever** [comment]
好的，使用愉快！
