### ISSUE TITLE
macOS install error

### ISSUE THREAD

**Issue by zmyer** [LER0ever/EverVim#11]
E492: 不是编辑器的命令: Plug 'scrooloose/nerdcommenter'
第   12 行:
E492: 不是编辑器的命令:     Plug 'Chiel92/vim-autoformat'
第   16 行:
E492: 不是编辑器的命令: Plug 'chrisyip/AuthorInfo'
第   17 行:
E492: 不是编辑器的命令: Plug 'tpope/vim-commentary'
第   18 行:
E492: 不是编辑器的命令: Plug 'godlygeek/tabular'
第   19 行:
E492: 不是编辑器的命令: Plug 'luochen1990/rainbow'
第   20 行:
E492: 不是编辑器的命令: Plug 'terryma/vim-multiple-cursors'
第   22 行:
E492: 不是编辑器的命令:     Plug 'majutsushi/tagbar'
第   24 行:
E492: 不是编辑器的命令: Plug 'MarcWeber/vim-addon-mw-utils'
第   25 行:
E492: 不是编辑器的命令: Plug 'tomtom/tlib_vim'
第   35 行:
E492: 不是编辑器的命令: Plug 'tpope/vim-dispatch'
处理 /Users/xuanyin/.EverVim/plugins/python/python.bundles 时发生错误:
第    3 行:
E492: 不是编辑器的命令: Plug 'python-mode/python-mode'
第    4 行:
E492: 不是编辑器的命令: Plug 'yssource/python.vim'
第    6 行:
E492: 不是编辑器的命令: Plug 'vim-scripts/python_match.vim'
处理 /Users/xuanyin/.EverVim/plugins/javascript/javascript.bundles 时发生错误:
第    2 行:
E492: 不是编辑器的命令: Plug 'elzr/vim-json'
第    3 行:
E492: 不是编辑器的命令: Plug 'pangloss/vim-javascript'
第    4 行:
E492: 不是编辑器的命令: Plug 'briancollins/vim-jst'
第    5 行:
E492: 不是编辑器的命令: Plug 'kchmck/vim-coffee-script'
处理 /Users/xuanyin/.EverVim/plugins/typescript/typescript.bundles 时发生错误:
第    2 行:
E492: 不是编辑器的命令: Plug 'Quramy/tsuquyomi'
第    3 行:
E492: 不是编辑器的命令: Plug 'HerringtonDarkholme/yats.vim'
第    4 行:
E492: 不是编辑器的命令: Plug 'Shougo/vimproc.vim', {'do' : 'make'}
处理 /Users/xuanyin/.EverVim/plugins/html/html.bundles 时发生错误:
第    2 行:
E492: 不是编辑器的命令: Plug 'alvan/vim-closetag'
第    3 行:
E492: 不是编辑器的命令: Plug 'hail2u/vim-css3-syntax'
第    4 行:
E492: 不是编辑器的命令: Plug 'gorodinskiy/vim-coloresque'
第    5 行:
E492: 不是编辑器的命令: Plug 'tpope/vim-haml'
第    6 行:
E492: 不是编辑器的命令: Plug 'wavded/vim-stylus'
第    7 行:
E492: 不是编辑器的命令: Plug 'posva/vim-vue'
第    8 行:
E492: 不是编辑器的命令: Plug 'mattn/emmet-vim'
第    9 行:
E492: 不是编辑器的命令: Plug 'digitaltoad/vim-pug'
处理 /Users/xuanyin/.EverVim/plugins/css/css.bundles 时发生错误:
第    1 行:
E492: 不是编辑器的命令: Plug 'hail2u/vim-css3-syntax'
第    2 行:
E492: 不是编辑器的命令: Plug 'groenewege/vim-less'
处理 /Users/xuanyin/.EverVim/plugins/misc/misc.bundles 时发生错误:
第    2 行:
E492: 不是编辑器的命令: Plug 'vimwiki/vimwiki'
第    3 行:
E492: 不是编辑器的命令: Plug 'tpope/vim-cucumber'
第    4 行:
E492: 不是编辑器的命令: Plug 'cespare/vim-toml', {'for': 'toml'}
第    5 行:
E492: 不是编辑器的命令: Plug 'quentindecock/vim-cucumber-align-pipes'
第    6 行:
E492: 不是编辑器的命令: Plug 'saltstack/salt-vim'
第    7 行:
E492: 不是编辑器的命令: Plug 'ryanss/vim-hackernews'
第    8 行:
E492: 不是编辑器的命令: Plug 'itchyny/calendar.vim'
处理 /Users/xuanyin/.EverVim/plugins/go/go.bundles 时发生错误:
第    3 行:
E492: 不是编辑器的命令: Plug 'fatih/vim-go', {'for': 'go'}
处理 /Users/xuanyin/.EverVim/plugins/rust/rust.bundles 时发生错误:
第    2 行:
E492: 不是编辑器的命令: Plug 'rust-lang/rust.vim'
第    3 行:
E492: 不是编辑器的命令: Plug 'racer-rust/vim-racer'
处理 /Users/xuanyin/.EverVim/plugins/cpp/cpp.bundles 时发生错误:
第    2 行:
E492: 不是编辑器的命令: Plug 'octol/vim-cpp-enhanced-highlight'
第    3 行:
E492: 不是编辑器的命令: Plug 'vim-scripts/c.vim'
第    4 行:
E492: 不是编辑器的命令: Plug 'vim-scripts/a.vim'
处理 /Users/xuanyin/.EverVim/plugins/lua/lua.bundles 时发生错误:
第    2 行:
E492: 不是编辑器的命令: Plug 'WolfgangMehner/lua-support'
处理 /Users/xuanyin/.EverVim/plugins/plugins.vim 时发生错误:
第   46 行:
E117: Unknown function: plug#end

**Comment by LER0ever** [comment]
你好，麻烦确认一下安装过程中没有报错，并且 plug.vim 在~/.vim/autoload/目录下。另外如果可以的话请提供一下Vim/NVim版本。

**Comment by zmyer** [comment]
对的，plug.vim在~/.vim/autoload/下面，安装过程没有报错，NVIM的版本是0.2.0

**Comment by LER0ever** [comment]
那请确认一下 nvim 中输入 `:set rtp?` 返回的路径中包含 `~/.config/nvim`。

(我手头现在没有macOS的机器，所以在Linux下重新部署了一遍，但是没能复现)

**Comment by zmyer** [comment]
:set rtp?
  runtimepath=~/.config/nvim,/etc/xdg/nvim,~/.local/share/nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/usr/local/Cel
lar/neovim/0.2.0/share/nvim/runtime,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,~/.local/share/nvim/site/after,/et
c/xdg/nvim/after,~/.config/nvim/after

**Comment by LER0ever** [comment]
你好，我刚刚在全新安装的macOS下部署了，没能复现。

看你的rtp中已经有了`~/.config/nvim`，所以neovim会自动加载该目录下的autoload，也就是链接到`~/.EverVim/autoload`，所以可能出问题的地方：
- 安装过程中没能成功创建软链接，请检查`~/.config/nvim`是否正确的链接到了`~/.EverVim`
- 再次跑一遍安装脚本，确认plug.vim下载完全


我来把我的安装过程贴上来
![image](https://cloud.githubusercontent.com/assets/10568668/26499626/e65609ec-4265-11e7-854e-d5cf70fc5af7.png)
![image](https://cloud.githubusercontent.com/assets/10568668/26499639/f3a0b73c-4265-11e7-9546-e74daf0d0aef.png)
![image](https://cloud.githubusercontent.com/assets/10568668/26499647/fa4d9726-4265-11e7-8374-163b4e152450.png)

**Comment by zmyer** [comment]
我应该知道问题出在哪了，多谢了，plug.vim这这货的路径有问题

**Comment by zmyer** [comment]
MacBook-Air-6:server$ nvim
YouCompleteMe unavailable: requires Vim compiled with Python (2.6+ or 3.3+) support
UltiSnips requires py >= 2.7 or py3

**Comment by LER0ever** [comment]
这个错误是因为你没有安装python-neovim，打开终端跑一下 pip3 install neovim 安装neovim的Python支持库，然后可能还需要去YouCompleteMe文件夹中运行 install.py，之后自动补全就可以用了。

**Comment by LER0ever** [comment]
Close as invalid. Feel free to reopen.
