### ISSUE TITLE
Icon is garbled in terminal and iterm2 but correct in macvim

### ISSUE THREAD

**Issue by lhcalibur** [LER0ever/EverVim#13]
![image](https://cloud.githubusercontent.com/assets/13448022/26666871/dade29d2-46d4-11e7-97a7-adcb1106dcc5.png)

system: macOs Sierra 10.12.5

**Comment by LER0ever** [comment]
Hi, if you're using vim **inside a terminal emulator**, you need to **set the terminal font to "Knack Nerd Font"** as described in [the instruction](https://github.com/LER0ever/EverVim/wiki/Installation-on-macOS). (GUI clients like MacVim would set the font for you automatically.)

It should look like this:
![image](https://cloud.githubusercontent.com/assets/10568668/26667712/1591d89a-46d9-11e7-98b7-85e01e11c2f9.png)

I'll add a font check at startup to make sure that font is properly installed (maybe later this week).

**Comment by LER0ever** [comment]
Your font settings should look like this (iTerm2 in this case):
![image](https://cloud.githubusercontent.com/assets/10568668/26667773/60a69f28-46d9-11e7-81b2-c6bb613fd2c0.png)

**Comment by lhcalibur** [comment]
It works, thank you so much!
