### ISSUE TITLE
怎么开启自动提示功能？

### ISSUE THREAD

**Issue by jay763190097** [LER0ever/EverVim#14]
~/.vim/bundle已装neocomplete.vim,但是还是没有代码提示？windows的安装文档能写详细一点么？

**Comment by LER0ever** [comment]
你好，在Windows下如果你的Vim有 +lua 支持的话neocomplete会自动启用。
请检查一下启动屏是否显示+Lua，如果显示的是-Lua的话你可能需要下载一份lua53.dll 放入Vim根目录下。

（如果是Windows的neovim的话，就需要使用YouCompleteMe，因为目前neovim没有lua client实现。）

**Comment by jay763190097** [comment]
![image](https://github.com/jay763190097/gvim-available/raw/master/QQ%E6%88%AA%E5%9B%BE20170606093423.png)
还是没有自动提示，neocomplete已装好的

**Comment by LER0ever** [comment]
@jay763190097 我来图文演示一下。

`:version`里的 `+lua/dyn` 表示这份Vim需要Lua的动态链接库才能正常使用 Lua Client 的功能，请检查一下你的Vim目录下有没有Lua53.dll 或者 Lua.dll, 如果没有的话需要去[Lua Binaries](http://luabinaries.sourceforge.net/download.html)下载一份`Lua-5.3.3_Win*-bin.zip`的文件并且将里面的Lua53.dll放入根目录。需要像这样：
* * *
![image](https://cloud.githubusercontent.com/assets/10568668/26816727/bd968f46-4ac5-11e7-81da-f3351d9e4706.png)
* * *
**并且确保启动屏（是启动屏不是:version）中有 "+Lua"，(如图中间的`{-Python3|-Python|+Lua}`):**
* * *
![image](https://cloud.githubusercontent.com/assets/10568668/26816771/fd319376-4ac5-11e7-8916-a54ea30c093a.png)
* * *
我重新部署了一遍，只要启动屏检测到+Lua，neocomplete就可以正常工作。
如果还是不行，**看看`:message`有没有任何错误信息。**

------------

_Windows的文档我今天会更新一下，顺便加上 YouCompleteMe 的安装指南。_

**Comment by wjh756381193** [comment]
我这里通过.EverVim.vimrc设置主题总是不成功！ 但是在编辑器中直接输入 :color mopkai 这样的方式则是可以成功切换主题的，请问这个是什么原因？ 一旦我创建了 .vimrc 文件，系统就不会再调用EverVim了，而是直接调用系统自身的vim工具了，请问，什么原因？
