### ISSUE TITLE
通过.EverVim.vimrc文件设置主题失败

### ISSUE THREAD

**Issue by wjh756381193** [LER0ever/EverVim#15]
我这里通过.EverVim.vimrc设置主题总是不成功！ 但是在编辑器中直接输入 :color mopkai 这样的方式则是可以成功切换主题的，请问这个是什么原因？ 一旦我创建了 .vimrc 文件，系统就不会再调用EverVim了，而是直接调用系统自身的vim工具了，请问，什么原因？

**Comment by LER0ever** [comment]
你好，这个问题在最新的commit [e3940f](https://github.com/LER0ever/EverVim/commit/e3940fdea0c3c80af800ca763eeea902bb6605cd)中已经修复，只需要在 .EverVim.vimrc 中设置如下
```viml
let g:evervim_color_theme="mopkai"
let g:evervim_airline_theme="mopkai"
```
以上两行的效果：
![image](https://cloud.githubusercontent.com/assets/10568668/26827026/e39eaf2a-4aed-11e7-8eaa-4aa9c77a0097.png)

你可以把上方的mopkai 替换成任意vim color 的名称，airline也是一样

**Comment by wjh756381193** [comment]
我通过你的上一个提交解决了主题不能加载的问题，现在出现了一个新的问题：
我在.EverVim.vimrc中修改了主题为我要的主题（mint）当每次使用vim打开文件的时候，提示：
lightline.vim: Could not load colorscheme mint.
但是我直接Enter进入文件，主题实际已经加载成功，如图

![Uploading QQ20170607-102030.png…]()
我的配置如下：

```
let g:evervim_color_theme="mint"
let g:evervim_airline_theme="mint"
```

**Comment by wjh756381193** [comment]
我通过你的上一个提交解决了主题不能加载的问题，现在出现了一个新的问题：
我在.EverVim.vimrc中修改了主题为我要的主题（mint）当每次使用vim打开文件的时候，提示：
lightline.vim: Could not load colorscheme mint.
但是我直接Enter进入文件，主题实际已经加载成功，如图

![qq20170607-102010](https://user-images.githubusercontent.com/5608970/26860657-aa7d3eda-4b71-11e7-94de-2417e72988c0.png)
![qq20170607-102030](https://user-images.githubusercontent.com/5608970/26860658-b04b324a-4b71-11e7-924e-9513ca842e75.png)

我的配置如下：

```
let g:evervim_color_theme="mint"
let g:evervim_airline_theme="mint"
```

注：只开启了这两行

**Comment by LER0ever** [comment]
因为lightline 并没有这个主题，lightline的主题和vim自身的colorscheme是分开的。Vim Color 总共有735个主题，而lightline的主题是他们自己内置的，完整的列表请查看 [这里](https://github.com/itchyny/lightline.vim/tree/master/autoload/lightline/colorscheme)。当然有一部分的Vim Color会内置一份lightline的主题，具体的你可能要试了才知道。

**Comment by wjh756381193** [comment]
Solved!
我试了一下，确实如你所讲！
那我有个猜想，是不是可以把VimColor中的主题直接拷贝到lightline的主题中使用呢？

**Comment by wjh756381193** [comment]
刚才我试了一下直接拷贝系统主题到lightline的主题目录下，并修改配置文件，发现并没有解决上面的问题！那么，我该怎么使用系统的主题且不让它报出警告呢？

**Comment by LER0ever** [comment]
> 那我有个猜想，是不是可以把VimColor中的主题直接拷贝到lightline的主题中使用呢？

这个不行诶。。。lightline 和 VimColor 定义方式是不一样的，兼容的可能性不大。
 
如果你实在想用更多的状态栏主题的话，请在 .EverVim.vimrc 中加入 `let g:evervim_use_airline = 1` 来使用[vim-airline](https://github.com/vim-airline/vim-airline)而不是lightline。airline的主题支持会稍微好一些，不少Vim Color都单独为airline适配过(如默认的Dracula)，而且airline本身自带了[好多主题](https://github.com/vim-airline/vim-airline-themes)。
