### ISSUE TITLE
nnoremap 映射快捷键不生效

### ISSUE THREAD

**Issue by lostsummer** [LER0ever/EverVim#16]
比如在.EverVim.vimrc 中写
`nnoremap <leader>gl :YcmCompleter GoToDeclaration<CR>`
不能生效，那该如何实现ycm的Goto跳转快捷键呢

**Comment by LER0ever** [comment]
YCM 的 GoToDeclaration 绑定为 `<Leader>gtc`，GoTo为 `<Leader>gto`。
在 .EverVim.vimrc 中不能绑定是因为vim先读了这个文件，而插件配置在这之后，所以有重复绑定就会被后面的覆盖掉。
 
YCM 具体的键位定义在 [plugins/youcompleteme/youcompleteme.vim](https://github.com/LER0ever/EverVim/blob/master/plugins/youcompleteme/youcompleteme.vim#L11-L13)
