### ISSUE TITLE
keymap issue

### ISSUE THREAD

**Issue by hzdtony** [LER0ever/EverVim#18]
I am use Mac OSx,I have update Evervim the latest version,  and used vim 8.0.685. I may be find a problem, when i every  time open the vim, the plugins always update, and the code snippet still not used, when i press <C-j> ,generate a new line, rather than I want to code snippet. I used terminal software is the iterms. Help me solve the problem,Thanks very much.

**Comment by LER0ever** [comment]
HI, thanks for reporting this issue. EverVim will try installing the plugins if the folder `~/.EverVim/bundle` does not exist, see [functions.vim#L143-L147](https://github.com/LER0ever/EverVim/blob/master/core/functions.vim#L143-L147). Can you make sure you have that folder?

For the code snippets keybindings, the `<C-j>` is currently mapped to `<C-w>j` for easier window navigation. If you use snippets very often, I suggest add the following line in `~/.EverVim.vimrc`: `let g:evervim_no_easyWindows = 1` to make the `<C-j>` work for snippets. 
(I'll fix this conflicting keymap tonight.)

**Comment by LER0ever** [comment]
I've updated the ultisnips keybindings. I can expand the snippet when type `date <Leader><Tab>` for example, it would turn into the current date. And jumping seems only work when Ycm autocompleting menu is on. You can choose one to expand after your type `date`, it would give you `date`, `datetime`, etc.

I'm not sure if that's what you want. (I don't use snippets very often anyway.)

**Comment by hzdtony** [comment]
Hi
Thanks you reply,I very hope release Evervim use manual. I now can use <Leader><Tab> completed code  snippet.I use <Leader> is "," rather than key "\".I don't know keymap condition,I only  view config file, such as need spend my vastly time. I hope a  clear and simple use manual.Thanks very much again.



At 2017-06-28 14:59:07, "L.E.R" <notifications@github.com> wrote:


I've updated the ultisnips keybindings. I can expand the snippet when type date <Leader><Tab> for example, it would turn into the current date. And jumping seems only work when Ycm autocompleting menu is on. You can choose one to expand after your type date, it would give you date, datetime, etc.

I'm not sure if that's what you want. (I don't use snippets very often anyway.)

**Comment by LER0ever** [comment]
> Thanks you reply,I very hope release Evervim use manual.

Will do. I've already added some keymapping manual in the Github Wiki. You can expect more documentation to come.

> I use <Leader> is "," rather than key "\"

The default Leader is `,`. And you can always use `<Space>` to trigger Leader Guide if your forget a specific key binding.

Closing this for now, and feel free to reopen.
