### ISSUE TITLE
:PlugInstall 提示不是编辑器命令

### ISSUE THREAD

**Issue by frostRed** [LER0ever/EverVim#19]
运行脚本

> All done with this script, now run vim/neovim and execute ":PlugInstall"

然后在nvim和vim都说PlugInstall不是编辑器命令。

**Comment by LER0ever** [comment]
你好，发issue请提供操作系统平台及vim版本。

`:PlugInstall` 是Vim-Plug的命令，请检查一下 安装过程有没有报错 以及 `~/.vim/autoload/plug.vim`是否存在。

**Comment by frostRed** [comment]
OS: Manjaro
vim: 8.0
neovim: 0.2.0

安装无任何错误或警告，`~/.vim/autoload/plug.vim`存在

**Comment by LER0ever** [comment]
请尝试执行一下下面几行bash，一行一行复制进去就行。
```bash
cd ~
sudo pacman -S git curl neovim python-neovim ctags
rm -rf ~/.EverVim ~/.vim ~/.config/nvim
git clone https://github.com/LER0ever/EverVim ~/.EverVim
cd .EverVim
sh Boot-EverVim.sh
nvim
```

我这边同样Manjaro没什么问题
![image](https://user-images.githubusercontent.com/10568668/27767689-cb8cb140-5f31-11e7-9161-df1f65847ed4.png)

**Comment by frostRed** [comment]
嗯，把原来的配置彻底删除，再安装果然没问题了，谢谢你。

**Comment by frostRed** [comment]
还有一个问题，看了文档，`echo Plug \'baabelfish/nvim-nim\' >> ~/.EverVim.vimrc`

往配置文件末尾添加了`Plug 'baabelfish/nvim-nim'`，但`:PlugInstall`后并没有自己安装，还是`E492: Not an editor command: Plug 'baabelfish/nvim-nim'`

**Comment by LER0ever** [comment]
最新的[a367c64](https://github.com/LER0ever/EverVim/commit/a367c64c1d031023e711d9593b15cb8842c524cb)修了自定义插件的文件。请将 `Plug 'baabelfish/nvim-nim'` 加入 `~/.EverVim.bundles`，也就是 `echo Plug \'baabelfish/nvim-nim\' >> ~/.EverVim.bundles`, 稍后我更新文档。

**Comment by LER0ever** [comment]
I'll close this as fixed? Feel free to reopen.
