### ISSUE TITLE
.hs文件保存时报错

### ISSUE THREAD

**Issue by tuberry** [LER0ever/EverVim#22]
保存haskell文件时报错：
`Error detected while processing BufWritePost Auto commands for "*.hs":
E492: Not an editor command: GhcModCheckAndLintAsync
`
我在Google搜索了一下，得到的一个[解决方案](https://github.com/spf13/spf13-vim/issues/625)。所以我把`~/.vim/plugins/haskell/ghcmod.vim`第一行中的`ghcmod`改为`ghc-mod`,但是依旧报错。其后我将`autocmd BufWritePost *.hs GhcModCheckAndLintAsync`
整行注释，依旧没有效果。请问问题出在哪？

**Comment by LER0ever** [comment]
> Not an editor command: 

这个意思是你打开了haskell的bundle，但是没有安装插件。
请尝试运行 :PlugInstall 或者在启动屏的时候按u更新。

**Comment by tuberry** [comment]
@LER0ever 已更新，但依然报错

**Comment by LER0ever** [comment]
> 已更新，但依然报错

- 先把你做的更改改回去，错误不是那一行判定导致的，然后
- 请确认你的系统上有ghc, ghc-mod, cabal 这三个命令
- 请确认在打开hs文件的时候可以执行 `:GhcModCheckAndLintAsync` 这个命令
- 如果仍然报错，请将报错后执行 `:messages` 的截图发一份上来

**Comment by tuberry** [comment]
@LER0ever 

- 已更改
- ghc,ghc-mod,cabal均已安装
- 执行`:GhcModCheckAndLintAsync`失败，显示`E492: Not an editor command: GhcModCheckAndLintAsync`
- 以下为`:messages`截图
![screenshot-2](https://user-images.githubusercontent.com/17917040/31613279-3216f9da-b2b5-11e7-9a6c-e0cc0bcd3272.png)
😞

**Comment by LER0ever** [comment]
> 执行:GhcModCheckAndLintAsync失败，显示E492: Not an editor command: 

好的我大概知道什么问题了，你可能没有开Haskell的bundle，所以ghcmod-vim 这个插件没有被安装。
EverVim的语言特性是通过不同的bundle group来开的，比如swift, elixir, haskell这些语言的高级支持默认是关闭的。

我已经把那一行配置改为只有开了Haskell支持才会执行，Commit [88991c](https://github.com/LER0ever/EverVim/commit/0adfa70bf00fb6c57692bba906dde3ef2388991c)

**Haskell的功能支持可以通过 `~/.EverVim.vimrc` 文件中的 `g:evervim_bundle_group` 来开启**，可以参考样例配置 [Example Configuration](https://github.com/LER0ever/EverVim/wiki/Example-Configuration)。更新过Bundle Group配置后需要刷新插件，直接启动屏按u即可。

**Comment by tuberry** [comment]
@LER0ever  谢谢，问题解决了。
