### ISSUE TITLE
NERDTree and fugitive error

### ISSUE THREAD

**Issue by Nanoc-ice** [LER0ever/EverVim#23]
It looks like there is an issue with running NERDTree with fugitive status.  The first opening of the NERDTree path generates the following messages:
Error detected while processing User Auto commands for "NERDTreeInit":
E121: Undefined variable: b:NERDTreeRoot
E116: Invalid arguments for function fugitive#detect

**Comment by LER0ever** [comment]
Hi @Nanoc-ice 
I don't think this "NERDTreeInit" is in the EverVim config (just try searching in this repo)
Could you please remove your old vim config prior to installing EverVim? 

On Linux/macOS that is:
```bash
cd ~
rm -rf .vim .config/nvim
rm -f .vimrc .gvimrc
# and then reinstall EverVim
```

If the problem still occur, please reply with your OS info, Vim version, and a `ls -ah` result in your home directory.

**Comment by Nanoc-ice** [comment]
I moved my .vim and .vimrc out of the way to the same effect.  On OS X with brew installed neovim (0.2.0).    
This is probably my environment, so I will spend some more time to clean it up to ensure it isn’t picking it up from somewhere else.

**Comment by Nanoc-ice** [comment]
It turns out there was something missing in NERDTree.  I updated everything this morning and NERDTree was updated and the log message was related to my issue.
So, the update resolved the issue.

**Comment by LER0ever** [comment]
Good to know. I'll close this issue as fixed.
