### ISSUE TITLE
neoVim doesn't work on Windows 10 after EverVim installation

### ISSUE THREAD

**Issue by YogliB** [LER0ever/EverVim#24]
This is what happens, when I run neoVim:

>PS ~\\.evervim> nvim
>Error detected while processing ~\\.EverVim\core\vimui.vim:
>line   21:
>E121: Undefined variable: g:evervim_color_theme
>E15: Invalid expression: 'color ' . g:evervim_color_theme
>Press ENTER or type command to continue

**Comment by LER0ever** [comment]
Hit enter, and the plugin installation process should automatically start. If not, type `:PlugInstall`.

**Comment by YogliB** [comment]
I hit Enter, and nothing happens.

**Comment by LER0ever** [comment]
Ok, then try `:PlugInstall` to start the plugin installation as described [here](https://github.com/LER0ever/EverVim/wiki/Installation-on-Windows)

**Comment by LER0ever** [comment]
Just tested a fresh installation on WIndows 10, assuming you managed to set it up as well?
Feel free to reopen this issue if not.
