### ISSUE TITLE
Install process doesn't change anything

### ISSUE THREAD

**Issue by skjorrface** [LER0ever/EverVim#25]
Hi. I'm using Ubuntu + Neovim +  Vundle as plugin manager. Following all steps in the documentation (both automatic and manual installation) doesn't seem to affect neovim. Even running :PluginInstall doesn't help.

**Comment by LER0ever** [comment]
Hi, you cannot really "use Vundle" as plugin manager, EverVim use "vim-plug" by default (it has all the features vundle has and its async). And for your problem, it seems like you haven't purged your previous old vim config. Please try doing the following in your terminal:

```bash
rm -rf .vim* .config/nvim # delete old config files
curl -sLf https://raw.githubusercontent.com/LER0ever/EverVim/master/Boot-EverVim.sh | bash
nvim # type :PlugInstall if the installation does not begin.
```

And if you encounter any problems while executing the Boot-EverVim.sh, you should check the prerequisite to make sure you have them all installed.

**Comment by skjorrface** [comment]
Thank you so much, replacing vundle with vim-plug and purging the old configuration did the trick.
