### ISSUE TITLE
How to disable "auto" folding while opening files

### ISSUE THREAD

**Issue by zzeroo** [LER0ever/EverVim#26]
Whats the prefered way to disable the automatic folding in Evervim.

**Comment by LER0ever** [comment]
Hi, you can do this by adding the following line to `~/.EverVim.vimrc` to override the global foldenable config:
```vim
autocmd FileType go set nofen
```
(**replace go** with the filetype you wish to turn off auto folding)
**nofen** here means "nofoldenable", and you can find the global default config for folding at [vimui.vim#L80](https://github.com/LER0ever/EverVim/blob/master/core/vimui.vim#L80)

**Comment by zzeroo** [comment]
Thank you for the explanation.
