### ISSUE TITLE
leader guide, how to set user-defined keymaps

### ISSUE THREAD

**Issue by robgrzel** [LER0ever/EverVim#27]
Hi!

In which file should I set this and in what format?

**Comment by LER0ever** [comment]
Hi @robgrzel , there are two files for user customization
- `~/.EverVim.vimrc` is for global user config that will override the default
- `YOUR_PROJECT/.EverVim.project` is for per-project settings that overrides the default and the global user config. You can just simply put this file in the project root directory.

As for user-defined keymappings, it's just how you normally define vim keymaps. You can add key mapping to one of those files above. For example
```vim 
" in one of your project root
" .EverVim.project
nnoremap <Leader>mb :!cd build; cmake ..; make -j
```
That will create a user-define keymap `<Leader>mb` to a command to use cmake to build the current project. 

Of course, leader M is just a vacant keymap prefix that I defined for user-defined kemaps, you can map it to for example `<Leader>dq` as long as that key mapping has not already been defined.

**Comment by robgrzel** [comment]
Nice! Thank You senior brother!
... Damn you are from 98? Why now I lost all my confidence, feel so weak in face of 13 old genius programmer 🗡
