### ISSUE TITLE
how to turn off wildfire

### ISSUE THREAD

**Issue by GreggJensen** [LER0ever/EverVim#28]
I don't like that wildfire has taken over my <CR>  I use return to go to the next line and now every time I hit return it highlights stuff and heaven forbid when I hit it a couple of times (to quickly go down a few lines).  I can see how the functionality in this plugin is very useful...just not for me.  I could find out to "not" pull in the plugin or how to turn it off correctly.  I can unmap <CR> once the editor is running but putting the command in ~/.Evervim.vimrc says its not mapped (plugin must not be loaded yet?)

**Comment by LER0ever** [comment]
Hi, I personally have the same experience for some of the plugins too, providing the functionality that I don't need.
I will add an options to disable a user-defined list of plugins so that we can still have the bundle  configuration with one or some plugins disabled.

**Comment by GreggJensen** [comment]
Great that would work.  I am anxious to try it out

**Comment by LER0ever** [comment]
Hi, @GreggJensen this issue should be fixed via [fd1f33](https://github.com/LER0ever/EverVim/commit/29edfeb568566e2a49c9a886dfffd0de4bfd1f33)

To disable a plugin or add additional plugin, you can switch on the option in .EverVim.vimrc
```vim
let g:override_evervim_bundles=1
```

And in the file `~/.EverVim.bundles` (create it if not exists)
```vim
UnPlug 'gcmt/wildfire.vim'
Plug 'Some additional plugins you like'
```

**Comment by Nanoc-ice** [comment]
Awesome, confirmed working!  
this can be closed
