### ISSUE TITLE
Not work in Centos 7

### ISSUE THREAD

**Issue by scarfase** [LER0ever/EverVim#34]
Hi. How to configure EverVim in centos 7? default install not work

**Comment by LER0ever** [comment]
Hi @scarfase ,

Please first make sure `git`, `curl`, `python3` is on your machine

Then try the following to install neovim: [neovim installation](https://github.com/neovim/neovim/wiki/Installing-Neovim#centos-7--rhel-7)

And then follow the [EverVim WikiL Installation on Linux](https://github.com/LER0ever/EverVim/wiki/Installation-on-Linux) to continue installation

If you still have any problem, please comment here with any possible error logs.

**Comment by scarfase** [comment]
Thanks, I'm idiot.
