### ISSUE TITLE
手动往.EverVim.bundles添加插件后，并不会自动下载

### ISSUE THREAD

**Issue by frostRed** [LER0ever/EverVim#37]
我添加了 `Plug 'wsdjeg/vim-chat'`， 然后运行 `nvim +PlugInstall`，并不会去下载插件

EverVim版本0.2.2
环境 Manjaro Kde 最新
Neovim 0.2.2-5

**Comment by LER0ever** [comment]
你好，这个是我文档没有写清楚，你需要在`.EverVim.vimrc`里加上一句

```vim
let g:override_evervim_bundles = 1
```

才会使它在启动的时候读取额外的bundles文件
