### ISSUE TITLE
How to use  vim-snippets?

### ISSUE THREAD

**Issue by hzdtony** [LER0ever/EverVim#4]
I open the python file,when me  input  "datetime" keyword,I how to selected relative snippet

**Comment by LER0ever** [comment]
Hi, the default keymap for Expanding the snippet is `<C-j>` in ultrsnips. You can map it to `<Enter>` or `<Tab>` if you want. 

The keymapping code is [here](https://github.com/LER0ever/EverVim/blob/master/plugins/youcompleteme/youcompleteme.vim#L15-L18), you are always welcome to remap the keybindings by overriding the variables in `~/.EverVim.vimrc`
