### ISSUE TITLE
Unable to update evervim

### ISSUE THREAD

**Issue by duytrung** [LER0ever/EverVim#42]
Hi,

I got these message when update evervim:

```
 Cloning into 'C:\Users\dell\.EverVim\bundle\vim-closetag'...
    fatal: unable to access 'https://git::@github.com/alvan/vim-closetag.git/': SSL certificate problem: self signed certificate in certificate chain

```
or something similar to this:

![image](https://user-images.githubusercontent.com/2046672/41641788-956f9f3e-74a5-11e8-8532-63ac547777b9.png)

How can I fix these errors?

Thanks so much.

TN

**Comment by LER0ever** [comment]
Hi, this is most likely your own git configuration problem. Please try git clone a repo and see if that works well. These errors are produced by vim-plug and what it does is simply call git in command line.
