### ISSUE TITLE
wrong "Before File" name ?

### ISSUE THREAD

**Issue by vlaw** [LER0ever/EverVim#46]
> Create a ~/.vimrc.before.local file to define any customizations that get loaded before the EverVim 
> .vimrc.
> quote from : <https://github.com/LER0ever/EverVim/wiki/Plugins#before-file>

I guess the name (`~/.vimrc.before.local`)  should be `~/.EverVim.vimrc`.
And  there are also some other places using `~/.vimrc.before.local` , 
see : <https://github.com/LER0ever/EverVim/search?q=~%2F.vimrc.before.local&type=Code>

**Comment by LER0ever** [comment]
@vlaw Hi, indeed, I removed the before file config a long time ago but haven't had the chance to update the wiki. Will do it tonight.
