### ISSUE TITLE
Can't disable folding and toolbar removal without modifying core.vim

### ISSUE THREAD

**Issue by etnoy** [LER0ever/EverVim#47]
Hi!

This is more of a question than an issue, but I'd thought I'd ask. I'm migrating from spf-13 and wanted to try Evervim. So far everything seems great, but I have one issue: I can't disable folding and put the toolbar buttons back.

The core of the issue appears to be that core.vim loads Evervim.vimrc before gui.vim, which means that the guioptions option is overridden. I see no way to put the T option back in guioptions without modifying core.vim to load Evervim.vimrc after all the Evervim files.

Did I miss something? Thanks :)

**Comment by LER0ever** [comment]
Hi @etnoy , you can open the fold by pressing zR (open all fold), but files are loaded with fold by default to allow better view on the large ones. I put all the necessary default configurations after loading EverVim.vimrc including hiding the menubar, mainly for the purpose of giving users a consistent experience on some mission critical options. Can I know what you need the menubar for?

I'm currently refactoring the whole codebase, and I might just set everything configurable with an optimized default.

**Comment by etnoy** [comment]
Folding is the type of thing I disable in my environment. It's basically impossible to edit TeX files with it enabled. As I'm migrating from another vim distro I expect to be able to disable folding.

Can I suggest making these types of non-standard features configurable to the user? For example, by having the user config loaded after the evervim config?

**Comment by LER0ever** [comment]
Sure, I'll make almost everything configurable in the next big update, but that will take a little bit of time (maybe up to months) since I'm currently very busy as a college student and I have other projects that needs to be worked on.

I'll leave this issue open until the customization is possible in master branch.

**Comment by raviraa** [comment]
I got to overriding default options by writing my settings in a function and calling it when window is created(BufWinEnter)

```vim
function! MyConfig()
  let g:ale_open_list = 0
  set wrap
endfunction
autocmd BufWinEnter *.go :call MyConfig()
```

**Comment by tispratik** [comment]
Same with me, when i open MacVim, evervim_font_size does not seem to take effect.

**Comment by diraol** [comment]
:wave: Hi!

Any news over here?
