### ISSUE TITLE
关于neocomplete 无法工作

### ISSUE THREAD

**Issue by fatfish516** [LER0ever/EverVim#50]
#### 报错如图：
![vim启动页面](https://i.loli.net/2018/12/06/5c08835b09bfc.png)

<br />

#### 下载的lua，下载2个都不行，如下图：
![lua的文件](https://i.loli.net/2018/12/06/5c0884a1166b1.png)

<br />

#### 这二者分别解压出来放到vim 的安装目录里，如下图：
![vim安装目录](https://i.loli.net/2018/12/06/5c08852bd764c.png)

<br />
但是启动gvim 还是报错 : 
提示  ![微信截图_20181206101419.png](https://i.loli.net/2018/12/06/5c08860ca162f.png)

请问这种情况怎么办？

**Comment by fatfish516** [comment]
最后还是启动报错 ![微信截图_20181206101419.png](https://i.loli.net/2018/12/06/5c08860ca162f.png)

**Comment by LER0ever** [comment]
@fatfish516 你好啊，看到你下的两个都是64bit的，如果你在用32位的Vim的话请尝试下载32bit的Lua二进制

**Comment by fatfish516** [comment]
💯 笑哭。。。。。我下载的gvim 8.1 居然是 32bit的/。。。

解决了  多谢
