### ISSUE TITLE
windows script tries to delete init.vim even if not exists

### ISSUE THREAD

**Issue by flyingrx** [LER0ever/EverVim#8]
按照流程来到 .\Boot... 那一步会出现一些错误。

**Comment by flyingrx** [comment]
![Uploading QQ图片20170508214702.png…]()

**Comment by flyingrx** [comment]
![qq 20170508214702](https://cloud.githubusercontent.com/assets/17722981/25807266/c93a8274-3438-11e7-9ef5-462b308e3956.png)

**Comment by LER0ever** [comment]
你好，这是因为我在安装脚本中硬编码了删除init.vim 和 ginit.vim 防止文件冲突，**安装过程是成功的**，在Vim中跑:PlugInstall 就好了。（主要是我不大擅长写PowerShell）
下次更新我会尝试在老版本Windows上全新安装，确保安装脚本兼容Windows 7 +。

**Comment by flyingrx** [comment]
但是打开GVIM后会有错误，点击ok后进入命令模式，安装命令无法启动
![image](https://cloud.githubusercontent.com/assets/17722981/25807894/ef3d0da0-343a-11e7-9d1e-0b1de1b3ad63.png)

**Comment by flyingrx** [comment]
![image](https://cloud.githubusercontent.com/assets/17722981/25808150/c2ead1be-343b-11e7-9a12-39c4788fb921.png)

**Comment by LER0ever** [comment]
抱歉，这个应该是vim-plug都没能正确加载，我晚上考完试重新写一下 Windows 安装脚本。

**Comment by flyingrx** [comment]
好的，辛苦了，祝取得好成绩。

**Comment by LER0ever** [comment]
最近两次commit修复了出错的脚本，建议删掉 %LOCALAPPDATA%/nvim，~/vimfiles，~/.EverVim.vimrc，~/.EverVim 这些文件后重新安装试一下。

**Comment by LER0ever** [comment]
@flyingrx 你好，打开GVim报错的问题已在issue #5 中修复了，具体commit为[e8c4a3a](https://github.com/LER0ever/EverVim/commit/e8c4a3a9f0546501fe2f4617a715a03cc28007fa)

如果安装仍然有问题，请随时重新打开issue。
