### ISSUE TITLE
Auto indent on save a python file make the file ruined

### ISSUE THREAD

**Issue by jamesgangchen** [LER0ever/EverVim#9]
Auto indent on save a python file make the file ruined
How can I switch this function off, thanks!

**Comment by LER0ever** [comment]
It uses vim-autoformat as a formatter, which means, if you have yapf or autopep8 installed on your system, the formatter will automatically format your python file into pep8 standard. If no formatter is available, it may fallback to vim's own formatter based on shiftwidth and tab settings, which is very likely what you've encountered. You can either install a pep8 formatter or just disable the vim-autoformat plugin using vim-plug. I'll implement an option for disable auto format in one hour.

**Comment by LER0ever** [comment]
This should be solved by [52adbcc](https://github.com/LER0ever/EverVim/commit/52adbcc228674b30b9097e69206fc5b73efabc9d).

You can now add `let g:evervim_no_autoformat = 1` to your `~/.EverVim.vimrc` to disable automatic format.
 (Still, I strongly suggest you should install the pep8 formatter.)

Feel free to reopen the issue if you still have problems with auto formatting!
